- name: variables from inventory
  hosts: mongodb
  tasks:
    - name: print the variables from inventory
      ansible.builtin.debug:
        msg: "mongodb user is {{MONGO_USERNAME}} and password is {{password}}"