- name: check if the user exits or not
  hosts: localhost
  tasks:
    - name: check if the user exists or not
      ansible.builtin.command: id roboshop
      register: out    # This directive registers the result of the command into a variable named 'out'
      ignore_errors: true # allows the playbook to continue executing even if the command fails.
    
    - name: print the output of the above command
      ansible.builtin.debug:
        msg: "output is: {{out}}"  

    - name: print exit status
      ansible.builtin.debug:
        msg: "{{out.rc}}"   

    - name: create user roboshop
      become: yes   # we need sudo access for this task.
      ansible.builtin.user:
        name: roboshop
      when: out.rc!=0       

# To dynamically check if a user exists on a target system and then create it if it doesn't exist
# check if a directory exists or not and create it is not existed.  