- name: print the names using loops
  hosts: localhost
  become: yes
  tasks:
    - name: print the names using the loops concept
      ansible.builtin.debug:
        msg: "names are {{item}}"
      loop:
        - sriram
        - raju
        - phani  