- name: Install and nginx and start the service
  hosts: mongodb
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name: start service
      ansible.builtin.service:
        name: nginx
        state: started    


# ansible-playbook -i inv -e ansible_user=centos -e ansible_password=DevOps321 nginx-install.yaml